### ISSUE TITLE
Переменные для галочек в json сделать понятными

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#127]
1) не можем понять какая галочка отвечает за какую переменную для всех галочек на скрине ниже

2) Нужно убрать 2 настройки они дублируются (см. скрин). 

![image](https://user-images.githubusercontent.com/18662965/43925175-3c128cec-9c2f-11e8-9d75-77218eca008a.png)

**Comment by TemkaHD** [comment]
+
