### ISSUE TITLE
Структура json файла с настройками

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#151]
Это расшифровка настроек из json, как мы её поняли 
[NazvPoley.docx](https://github.com/GloomlySeth/GOST/files/2723602/NazvPoley.docx)

Это образец из json файла которому нужно следовать
[default.docx](https://github.com/GloomlySeth/GOST/files/3026878/default.docx)

   1) Json приводим в соответствие с этим доковским файлом. 
   2) Все настройки, которые добавились в связи с нашей работой по их добавлению, дописываем в конец файла json. В  документе default.docx помечаем, что это за настройка, чтобы можно было понять и использовать её по назначению.  
   3) Если какая-то из настроек из фронтэнда удалена, то на её место в json нужно вставить другую настройку и в вордовском файле пометить, что за настройка вставлена вместо удалённой.
   4) В случае, если мы добавляем уровень заголовка или уровень списка, то настройки по добавленному уровню записываем в конец списка. И делаем так, чтобы можно было идентифицировать однозначно, что за группа настроек к чему она относиться к списку или к заголовкам.

**Comment by GloomlySeth** [comment]
ВНИМАНИЕ!
Обновил файл - default.docx

**Comment by Rynkevich17** [comment]
[default (1).docx](https://github.com/GloomlySeth/GOST/files/2808918/default.1.docx)
fid - id файла
did - id требования

**Comment by TemkaHD** [comment]
[default.docx](https://github.com/GloomlySeth/GOST/files/3026901/default.docx)
тот же файл только в исполнен в стиле json

**Comment by TemkaHD** [comment]
структура json 
[default.docx](https://github.com/GloomlySeth/GOST/files/3033314/default.docx)

**Comment by freedom00000** [comment]
было бы классно сделать как в зеленых кружках, вместо того чтобы как в красных (однообразно. к тому же для строк не нужны [])
![image](https://user-images.githubusercontent.com/10418363/55631630-2acea080-57c1-11e9-8b8d-1fe843259cfa.png)

**Comment by TemkaHD** [comment]
Нет проблем)


пт, 5 апр. 2019 г., 16:40 freedom00000 <notifications@github.com>:

**Comment by TemkaHD** [comment]
исправил все в соответствии с просьбами

**Comment by TemkaHD** [comment]
+
