### ISSUE TITLE
Переместились и поехали настройки для формул

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#16]
![8 _](https://cloud.githubusercontent.com/assets/18662965/24089990/75e580ae-0d4d-11e7-90e7-e7e96de6c59a.png)

Смотрю тут - http://wz.argoosnet.by/node/add/demand-create

См. правки на скриншоте. Нужно перепроверить с  прототипом. Если каких-то настроек не хватает, добавить.  

Плюс обязательно  учесть пожелания на нижеследующих скриншотах

![5 _](https://cloud.githubusercontent.com/assets/18662965/24090007/956a5f26-0d4d-11e7-9ac1-dfef7e6b4225.png)

![6 _](https://cloud.githubusercontent.com/assets/18662965/24090538/39381ae0-0d52-11e7-83e5-deb372dcadda.png)

**Comment by Rynkevich17** [comment]
Исправлено

**Comment by GloomlySeth** [comment]
Немного стелку неправильно поставил на прошлых скринах. 

![image](https://user-images.githubusercontent.com/18662965/33656440-22789836-da87-11e7-9121-4bdad5cc0ae7.png)

**Comment by Rynkevich17** [comment]
Исправил

**Comment by GloomlySeth** [comment]
Мой косяк. 

![image](https://user-images.githubusercontent.com/18662965/35957917-1d32b3ca-0caf-11e8-91bb-70243dab7d8c.png)

Если научишь, я такие вещи сам могу менять.
