### ISSUE TITLE
Сделать отображение процента выполнения обработки документа

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#165]
Сервер будет присылать цифры от 0 до 100. Это процент выполнения обработки файла.

Нужно сделать процессбар, на котором будут отображаться и визуализироваться эти значения. 

![default](https://user-images.githubusercontent.com/18662965/51323464-591dc900-1a79-11e9-9915-ccce3cd0c38c.png)

**Comment by freedom00000** [comment]
Алгоритм:
1) десериализуется полученный json с сайта
2) формируется объект Percents с полями fid, demand_id, percent 
3) поочередно выполняются методы для обработки doc, после каждого у объекта Percents меняется поле percent
4) объект Percents сериализуется и отправляется по адресу http://wz.argoosnet.by/processing_get_json/ (ContentType = "application/json" , Method = "POST")
5) 3 и 4 повторяется пока документ не будет обработан
