### ISSUE TITLE
Изменить наполнение настройки "Тип нумерации"

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#18]
![5 _](https://cloud.githubusercontent.com/assets/18662965/24090326/2ae69194-0d50-11e7-969e-48e8de524301.png)

применить изменения дна аналогичной настройки в разделах 
 - "Нумерация"
 - "Картинки"
 - "Таблицы"
 - "Формулы"

**Comment by Rynkevich17** [comment]
Изменил
