### ISSUE TITLE
Изменить структуру страницы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#182]
Встроить белую полоску и логотип с надписью на все страницы (см. скрин). 

Логотип сделать кликабельным. Клик по логотипу - переход на главную страницу  

![image](https://user-images.githubusercontent.com/18662965/54742368-44bd9000-4bd2-11e9-8fcb-8bc448f30660.png)

![змест](https://user-images.githubusercontent.com/18662965/54742488-a120af80-4bd2-11e9-8a72-3660486411f1.gif)
Если нужно как-то иначе сохранить файл с лого напишите в коменты - сделаю как нужно.

**Comment by TemkaHD** [comment]
лучше png либо svg

**Comment by GloomlySeth** [comment]
завтра сделаю. Какой размер? 
имеет значение?

**Comment by TemkaHD** [comment]
по хорошему подогнать под размер, что бы меньше памяти занимало, я могу сам перерисовать под нужны размер

**Comment by GloomlySeth** [comment]
зачем перерисовать. Есть фотошопный файл. Куда кинуть?

**Comment by TemkaHD** [comment]
можно тут прикрепить

**Comment by GloomlySeth** [comment]
Я уже пробовал. Не крепиться такой файл. Говорит: не поддерживается такой тип файла

**Comment by TemkaHD** [comment]
+
