### ISSUE TITLE
Сделать возможность редактирования требований

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#183]
На этой странице пропала возможность перейти к редактированию требований (http://wz.argoosnet.by/node/16)

 Должен быть переход на страницу типа "Формирование требований" с возможностью отредактировать что-то. Такая страница было, но почему-то пропала. 

![image](https://user-images.githubusercontent.com/18662965/54742696-2efc9a80-4bd3-11e9-80e9-3fb744e557a2.png)

**Comment by Rynkevich17** [comment]
редактировать можно под админом

**Comment by TemkaHD** [comment]
из под админа (не валидный таск)
