### ISSUE TITLE
Почему на странице так много красны строчек?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#189]
Загрузил документ sakovich.docx
Запустил его в обработку со страница "Звгрузка документа"
Увидел страницу, которая на скрине

![image](https://user-images.githubusercontent.com/18662965/55670683-363ccd00-5890-11e9-88c4-7b1dbc438019.png)

**Comment by TemkaHD** [comment]
исправил

**Comment by TemkaHD** [comment]
+
