### ISSUE TITLE
Не хватает настроек в разделе "Таблицы"

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#19]
В разделе настроек "Таблицы" отсутствуют группы настроек:
 -  "Размещение таблицы"
 -   "Нумерация"
 -   "Настройки нумерации"

  ВАЖНО!!! В разделе насроек  "Картинки" дваждыприсутствуют  "настройки нумерации", но не в полном составе. Сделать одинаково

**Comment by Rynkevich17** [comment]
Исправил
