### ISSUE TITLE
Добавить группу настроек "Шрифт"

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#22]
Нужно добавить такие настройки 

![default](https://cloud.githubusercontent.com/assets/18662965/24090720/de250080-0d53-11e7-8a82-5ff91dd4e30e.png)

в следующие разделы.
- "Нумерация"
- "Заголовки"
- "Содержание"
- "Картинки" в группы настроек "Настройки нумерации" и "Настройки подписи"
- "Таблицы" в группы настроек "Настройки нумерации" и "Настройки подписи"
- "Списки"

**Comment by Rynkevich17** [comment]
Добавил.
Json: 
[json.txt](https://github.com/GloomlySeth/GOST/files/1964559/json.txt)

**Comment by GloomlySeth** [comment]
В настройках "Картинки" забыл добавить эту опцию в "Настройки нумерации"
