### ISSUE TITLE
Неадекватное поведение кнопок "Настройки текста"

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#25]
![default](https://cloud.githubusercontent.com/assets/18662965/24282228/36b795aa-106f-11e7-978e-4043ad472480.png)

  Нельзя выключить жирный шрифт. Исчезают кнопки "Курсив" и "Подчёркивание", При их нажатии.

**Comment by Rynkevich17** [comment]
Баг повторялся? Не смог воспроизвести

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/32847613-86496fcc-ca3b-11e7-816e-0b94a90d16cd.png)

**Comment by Rynkevich17** [comment]
Какой браузер? У меня хром и мозила все кнопки показывают. Возможно, надо почистить кэш браузера

**Comment by GloomlySeth** [comment]
Это я дома смотрел. Сейчас в универе - всё отобраается. Как его чистить?

**Comment by Rynkevich17** [comment]
Ctrl+F5

**Comment by GloomlySeth** [comment]
Сделал. Везде нашлись кнопки, только в одном месте не нашлись
![image](https://user-images.githubusercontent.com/18662965/33152601-80f97842-cfee-11e7-902d-6ac891a036e0.png)

**Comment by Rynkevich17** [comment]
Исправлено

**Comment by Rynkevich17** [comment]
Исправлено
