### ISSUE TITLE
Цвет границы в настройках рисунка

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#27]
![default](https://cloud.githubusercontent.com/assets/18662965/24329269/0d19974c-120a-11e7-94b4-6a241841ccb3.png)

Реализовать какой-то из вариантов

**Comment by Rynkevich17** [comment]
Исправлено

**Comment by GloomlySeth** [comment]
зато новый баг появился

![image](https://user-images.githubusercontent.com/18662965/32847300-abe26b40-ca3a-11e7-9d3b-60f70a20c739.png)

**Comment by Rynkevich17** [comment]
Исправлено

**Comment by GloomlySeth** [comment]
Не учёл выровнять по одной линии эдиты этих трёх настроек. Ну да задно. Пусть так будет
