### ISSUE TITLE
Настройки основного текта

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#30]
![default](https://cloud.githubusercontent.com/assets/18662965/25334251/84424884-28f6-11e7-9565-64eff4469a16.png)

Привести в соответствие с образцом

**Comment by Rynkevich17** [comment]
![2 _](https://user-images.githubusercontent.com/20841784/32825123-c657777c-c9f4-11e7-9ba2-b398051d1691.png)
сделано по этим замечаниям
