### ISSUE TITLE
Размеры и цвет полей для ввода

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#31]
![1](https://cloud.githubusercontent.com/assets/18662965/25334345/040950e4-28f7-11e7-8711-dee48aa20f12.png)
![2](https://cloud.githubusercontent.com/assets/18662965/25334352/08c663e2-28f7-11e7-835c-354fca0323b6.png)

  Исправить как на картинках

**Comment by Rynkevich17** [comment]
Исправлено
