### ISSUE TITLE
Видимые элементы интерфейса

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#32]
![default](https://cloud.githubusercontent.com/assets/18662965/25335837/6e812310-28fd-11e7-9a07-074ddcb55073.png)
![1](https://cloud.githubusercontent.com/assets/18662965/25335858/7bec676c-28fd-11e7-9a94-b4f987d46c75.png)
![2](https://cloud.githubusercontent.com/assets/18662965/25335866/8166720a-28fd-11e7-814a-53c50473ce49.png)

  Сделать невидимым на проде елементы настроек полей, которые я првёл на картинках.

**Comment by GloomlySeth** [comment]
В скринах 2 и 3 сровнять цвет с фоном + убрать лишние кнопки и надписи

**Comment by Rynkevich17** [comment]
Исправлено
