### ISSUE TITLE
Описание страницы "Состояние счёта"

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#36]
Фактически стартовать можно и без неё. Т.к. вся информация на ней должна браться из реальных платежей пользователей. А этих платежей на старте работы не будет. 

 Однако, мы её сделаем в упрощённом виде. Как на картинке. 

![default](https://cloud.githubusercontent.com/assets/18662965/25808688/892ac178-3413-11e7-93e0-c6076c726815.png)

Если непонятно отрисовал, Пишите, буду пояснять

**Comment by Rynkevich17** [comment]
Сделал эту страницу http://wz.argoosnet.by/state-of-an-account
