### ISSUE TITLE
Кривая таблица на странице список документов

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#54]
![default](https://user-images.githubusercontent.com/18662965/29739028-98911d18-8a3c-11e7-880b-61dd8abe07fc.png)

   Либо на этой странице либо на странице с детальной информацией о документе нужно дать пользователю возможность изменить требования к оформлению документа, которые он применил для обработки при загрузке документа.

**Comment by Rynkevich17** [comment]
Список документов находится здесь: http://wz.argoosnet.by/document_list
На скрине "текущая таблица" список требований: http://wz.argoosnet.by/requirements_list

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/32598146-f93fdd32-c549-11e7-9f73-89912e7e8ae4.png)

**Comment by Rynkevich17** [comment]
Добавил иконки

**Comment by Rynkevich17** [comment]
Иконки есть, возможность изменять требования добавил.
