### ISSUE TITLE
Окно загрузки после нажатия кнопки загрузить

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#56]
![image](https://user-images.githubusercontent.com/18662965/29947017-5e174bbc-8eb0-11e7-8b92-c8dc4a04571f.png)

Либо переименовать кнопку "Remuve" в кнопку "Удалить". Либо сделать переход сразу на страницу вида : 

![image](https://user-images.githubusercontent.com/18662965/29947091-9aa4fa98-8eb0-11e7-9704-4a371e4f58d6.png)

**Comment by Rynkevich17** [comment]
Сделан второй вариант
