### ISSUE TITLE
Криво загружается со страницы "Список файлов"

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#69]
После загрузки и обработки файла перехожу на страницу "Список документов". 
Пытаюсь скачать обработанный файл через "Download"
Получаю окошко 
![image](https://user-images.githubusercontent.com/18662965/31253117-3fbd6650-aa2c-11e7-93ae-b062506b70d0.png)

Хочется, чтобы начиналась закачка файла.

**Comment by Rynkevich17** [comment]
Исправлено
