### ISSUE TITLE
Список документов 2

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#72]
На странице "Список документов" не работает кнопка "Обработать". 
Выделяю птичкой пару файлов для обработки, нажимаю кнопку "Обработать" - кидает на страницу "Загрузка документа".  Файлы не обрабатывает.

**Comment by GloomlySeth** [comment]
Решил совсем убрать кнопку "Обработать" Или это временная мера?

**Comment by Rynkevich17** [comment]
Ссылка осталась, я сейчас работаю над тем, чтобы она приобрела функционал

**Comment by GloomlySeth** [comment]
Можно ли сделать, чтобы пользователь смог поставить птички нескольким документам и они ушли на обработку?  (как на странице "список документов", так и на станице "Загрузка документа")

**Comment by GloomlySeth** [comment]
при нажатии кнопки обработать сейчас заставляет пройти определённый алгоритм - 3 окна с кнопками. Нужно сделать, чтобы страничка обновилась и в таблице изменилось состояние документа

**Comment by Rynkevich17** [comment]
Убрал один шаг подтверждения, теперь пользователь только выбирает требование и сразу начинает обработку
