### ISSUE TITLE
Не видно весь список загруженных документов. 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#78]
Если загрузить более 10 документов, то на странице "Список документов" нельзя просмотреть 11-й.

**Comment by GloomlySeth** [comment]
не нахожу, куда тискать, чтобы переключить страницу.

**Comment by Rynkevich17** [comment]
![_ - mozilla firefox 2017-10-30 09 17 55](https://user-images.githubusercontent.com/20841784/32157245-63468806-bd53-11e7-97ea-f7c4db4e07ed.png)
Под обычным пользователем у меня так, под админом тоже есть пагинатор. Должно быть больше 10 документов

**Comment by Rynkevich17** [comment]
Поправил футер, теперь пагинатор будет виден на разных разрешениях
