### ISSUE TITLE
Переносы слов на странице "Список документов"

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#90]
![image](https://user-images.githubusercontent.com/18662965/32765875-78990488-c91d-11e7-9e11-2e0046b061d0.png)

**Comment by Rynkevich17** [comment]
Исправил

**Comment by Rynkevich17** [comment]
Здесь, что-то не так, что опять открыто?

**Comment by GloomlySeth** [comment]
Это баг
