### ISSUE TITLE
Подровнять настройки раздела "Списки"

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/GOST#98]
![image](https://user-images.githubusercontent.com/18662965/33656846-72ffc076-da88-11e7-8f04-d4b9e401c15c.png)

**Comment by Rynkevich17** [comment]
Если уберу кнопки remove и add another item, то пользователь не сможет добавлять дополнительные подразделы нумерации в разделе списки. Нужна всего одна настройка нумерации или другие должны появляться по каким-то другим условиям?

**Comment by GloomlySeth** [comment]
Значит нужно их переименовать. 
"remove" - "удалить уровень списка"
"add another item" - "добавить уровень списка"

Не забудь добавить "Тип нумерации" (см. скрин)

**Comment by Rynkevich17** [comment]
Исправлено
